antkzn/users/urls.py
from django.urls import path

from antkzn.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path(
        "contact/",
        TemplateView.as_view(template_name="pages/contact.html"),
        name="contact",
    ),
    path(
        "blog/",
        TemplateView.as_view(template_name="pages/blog.html"),
        name="blog",
    ),
    path(
        "service/",
        TemplateView.as_view(template_name="pages/service.html"),
        name="service",
    ),
    path(
        "repair/",
        TemplateView.as_view(template_name="pages/repair.html"),
        name="repair",
    ),
    path(
        "improve/",
        TemplateView.as_view(template_name="pages/improve.html"),
        name="improve",
    ),
    path(
        "maintain/",
        TemplateView.as_view(template_name="pages/maintain.html"),
        name="maintain",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("antkzn.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

antkzn/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

antkzn/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

antkzn/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

antkzn/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

antkzn/templates/pages/contact.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  <!--Start breadcrumb area-->
  <section class="breadcrumb-area">
    <div class="container text-center">
      <h1>Contact Us</h1>
    </div>
  </section>
  <!--End breadcrumb area-->

  <!--Start breadcrumb bottom area-->
  <section class="breadcrumb-botton-area">
    <div class="container">
      <div class="left">
        <ul>
          <li><a href="index-2.html">Home</a></li>
          <li><i class="fa fa-caret-right" aria-hidden="true"></i></li>
          <li class="active">Contact Us</li>
        </ul>
      </div>
    </div>
  </section>
  <!--End breadcrumb bottom area-->

  <!--Start contact area-->
  <section class="contact-area">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="contact-info">
            <div class="title">
              <h2>Quick Contact</h2>
            </div>
            <div class="accordion-box">
              <!--Start single accordion box-->
              <div class="accordion accordion-block">
                <div class="accord-btn active"><h4>Headquarters</h4></div>
                <div class="accord-content collapsed">
                  <ul class="contact-info-list">
                    <li>
                      <div class="icon-holder">
                        <span class="flaticon-pin"></span>
                      </div>
                      <div class="text-holder">
                        <h5><span>321, Breaking Street,</span><br> 2nd cros, Newyork ,USA 10002</h5>
                      </div>
                    </li>
                    <li>
                      <div class="icon-holder">
                        <span class="flaticon-technology"></span>
                      </div>
                      <div class="text-holder">
                        <h5><span>Call Us</span><br>+321 4567 89 012 &amp; 79 023</h5>
                      </div>
                    </li>
                    <li>
                      <div class="icon-holder">
                        <span class="flaticon-interface"></span>
                      </div>
                      <div class="text-holder">
                        <h5><span>Mail Us</span><br>Support@aircare.com</h5>
                      </div>
                    </li>
                    <li>
                      <div class="icon-holder">
                        <span class="flaticon-clock"></span>
                      </div>
                      <div class="text-holder">
                        <h5><span>Opening Time</span><br>Mon - Sat: 09.00am to 18.00pm</h5>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <!--End single accordion box-->
              <!--Start single accordion box-->
              <div class="accordion accordion-block">
                <div class="accord-btn"><h4>Support Centre</h4></div>
                <div class="accord-content">
                  <ul class="contact-info-list">
                    <li>
                      <div class="icon-holder">
                        <span class="flaticon-pin"></span>
                      </div>
                      <div class="text-holder">
                        <h5><span>226, Breaking Street,</span><br> 2nd cros, Newyork ,USA 1002</h5>
                      </div>
                    </li>
                    <li>
                      <div class="icon-holder">
                        <span class="flaticon-technology"></span>
                      </div>
                      <div class="text-holder">
                        <h5><span>Call Us</span><br>+321 4567 89 012 &amp; 79 023</h5>
                      </div>
                    </li>
                    <li>
                      <div class="icon-holder">
                        <span class="flaticon-interface"></span>
                      </div>
                      <div class="text-holder">
                        <h5><span>Mail Us</span><br>Support@aircare.com</h5>
                      </div>
                    </li>
                    <li>
                      <div class="icon-holder">
                        <span class="flaticon-clock"></span>
                      </div>
                      <div class="text-holder">
                        <h5><span>Opening Time</span><br>Mon - Sat: 09.00am to 18.00pm</h5>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <!--End single accordion box-->
            </div>
          </div>
        </div>
        <div class="col-md-8">
          <div class="contact-form">
            <div class="title">
              <h2>Send Message Us</h2>
            </div>
            <form id="contact-form" name="contact_form" class="default-form"
                  action="http://steelthemes.com/demo/html/Aircare/inc/sendmail.php" method="post">
              <div class="row">
                <div class="col-md-6">
                  <input type="text" name="form_name" value="" placeholder="Your Name*" required="">
                </div>
                <div class="col-md-6">
                  <input type="email" name="form_email" value="" placeholder="Your Mail*" required="">
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <input type="text" name="form_phone" value="" placeholder="Phone">
                </div>
                <div class="col-md-6">
                  <input type="text" name="form_subject" value="" placeholder="Subject">
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <textarea name="form_message" placeholder="Your Message.." required=""></textarea>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <input id="form_botcheck" name="form_botcheck" class="form-control" type="hidden" value="">
                  <button class="thm-btn bg-1" type="submit" data-loading-text="Please wait...">send message</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--End contact area-->

  <!--Start Google map area-->
  <section class="google-map-area">
    <div
      class="google-map"
      id="contact-google-map"
      data-map-lat="44.529688"
      data-map-lng="-72.933009"
      data-icon-path="images/resources/map-marker.png"
      data-map-title="Brooklyn, New York, United Kingdom"
      data-map-zoom="12"
      data-markers='{
            "marker-1": [44.529688, -72.933009, "<h4>Head Office</h4><p>44/108 Brooklyn, UK</p>"],
            "marker-2": [44.231172, -76.485954, "<h4>Branch Office</h4><p>4/99 Alabama, USA</p>"]
        }'>

    </div>
  </section>
  <!--End Google map area-->
{% endblock content %}

antkzn/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

antkzn/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

antkzn/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}